project:
  type: website
  output-dir: docs

website:
  site-url: https://kareemnayfeh.github.io

format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: a11y-dark
    copy-code: true
