project:
  type: website
  output-dir: docs

website:
  site-url: https://kareemnayfeh.github.io
  title: "Kareem Nayfeh"
  navbar:
    title: false
    background: "#0d0e0f"
    foreground: light
    search: false
    collapse: false
    left:
      - text: "Everything"
        href: index.qmd
      - text: "Favorite Projects"
        href: favorites.qmd


filters:
  - last-edited.lua

format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: a11y-dark
    copy-code: true
